feed/urls.py
from django.urls import path 
from .views import HomePageView, PostDetailView, AddPostView

app_name = 'feed'

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('detail/<int:pk>/', PostDetailView.as_view(), name='detail'),
    path('post/', AddPostView.as_view(), name='post'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from feed import urls as feed_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(feed_urls, namespace='feed'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feed/models.py
from django.db import models
from sorl.thumbnail import ImageField

class Post(models.Model):
    title = models.CharField(max_length=20, blank=False, null=False)
    text = models.TextField(max_length=500, blank=False, null=False)
    image = ImageField()

    def __str__(self) -> str:
        return self.title

feed/forms.py
from django import forms

class PostForm(forms.Form):
    image = forms.FileField()
    title = forms.CharField(label="Title")
    text = forms.CharField(label="Description")

feed/views.py
from django.contrib import messages
from django.views.generic import TemplateView, DetailView, FormView
from .forms import PostForm
from .models import Post

class HomePageView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.all().order_by('-id')
        return context 

class PostDetailView(DetailView):
    template_name = "detail.html"
    model = Post

class AddPostView(FormView):
    template_name = "new_post.html"
    form_class = PostForm
    success_url = "/"

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        new_object = Post.objects.create(
            title=form.cleaned_data['title'],
            text=form.cleaned_data['text'],
            image=form.cleaned_data['image']
        )
        messages.add_message(self.request, messages.SUCCESS, 'Your post was successful')
        return super().form_valid(form)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Default title{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <style>
        body {
            background-color: black;
            background-image: url("media/nasa.jpg");
            background-size: cover;
            background-repeat: no-repeat;
        }
    </style>

</head>
<body>
    
    {% include "includes/navbar.html" %}

    {% if messages %}
        {% for message in messages %}
            <div class="bg-{% if message.tags %}{{ message.tags }}{% else %}success{% endif %} bg-gradient text-center text-white py-4">
                {{ message }}
        </div>
        {% endfor %}
    {% endif %}



    
    <div class="container">
        {% block body %}{% endblock %}
    </div>

</body>
</html>

templates/detail.html
{% extends "base.html" %}

{% block title %}{{ object.text }}{% endblock %}



{% block body %}
    <div class="row">
        <div class="col-sm-10 offset-2 text-white sm-1 py-5">
            <h1>{{ object.title }}</h1>
            <hr>
            <img src="{{ object.image.url }}" class="img-fluid rounded border border-primary">
            <hr>
            <p><h3>{{ object.text }}</h3></p>
        </div>
    </div>
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}BJJ Image Sharer{% endblock %}

{% block body %}
    <div class="row">
        {% for post in posts %}
            <div class="col-sm-6 col-md-3">
                <div class="card my-4">
                    {% thumbnail post.image "200x200" crop="center" as im %}
                        <img src="{{ im.url }}" class="card-img-top" alt="...">
                    {% endthumbnail %}
                    <div class="card-body">
                        <p class="card-title" style="title"><h3>{{ post.title }}</h3></p>
                        <a href="{% url 'feed:detail' post.id %}" class="btn btn-primary">Click for detials</a>
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="col-sm-6 offset-3 text-center text-white py-5 my-5">
                <h3>Welcome!</h3>
                <p>Add your first image</p>
                <a href="{% url 'feed:post' %}" class="btn btn-lg btn-primary">Upload Image</a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color:black;">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">BJJ Image Sharer</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'feed:index' %}">Home</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'feed:post' %}">Add New Image</a>
            </li>
        </ul>
      </div>
    </div>
  </nav>

templates/new_post.html
{% extends "base.html" %}

{% block title %}Upload a new image{% endblock %}

<style>
    body {
        background-color: black;
        background-image: url("media/nasa.jpg");
        background-size: cover;
        background-repeat: no-repeat;
    }
</style>

{% block body %}
    <form method="POST" action="" enctype="multipart/form-data" class="col-sm-4 offset-4 text-white py-5">
        <h2>Upload an image!</h2>
        {% csrf_token %}
        {{ form.as_p }}
        <div>
            <button type="submit" class="btn btn-lg btn-primary">Submit form</button>
        </div>
    </form>
{% endblock %}